const ids=['tonelaje','leyCu','leyAg','leyAu','h2o','merma','leyCuConc','alquiler','adelanto','cuPrice','agPrice','auPrice','pagableCu','deducCu','refCu','proteccion','pagableAg','deducAg','refAg','pagableAu','deducAu','refAu','maquila','analisis','traslado'];
const metaIds=['empresa','cliente','responsable','fecha','observaciones'];
const KEY='minero-yachaq-historico';
const $=id=>document.getElementById(id);
const n=id=>parseFloat($(id).value)||0;
const money=value=>Number.isFinite(value)?value.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const set=(id,value)=>$(id).textContent=value;
const dateLabel=value=>new Date((value||new Date().toISOString().slice(0,10))+'T12:00:00').toLocaleDateString('es-PE',{day:'2-digit',month:'long',year:'numeric'});
$('fecha').value=new Date().toISOString().slice(0,10);

function calculate(){
  const tonelaje=n('tonelaje'),leyCu=n('leyCu'),leyAg=n('leyAg'),leyAu=n('leyAu'),cu=n('cuPrice'),ag=n('agPrice'),au=n('auPrice'),h2o=n('h2o'),merma=n('merma'),leyConc=n('leyCuConc'),dedCu=n('deducCu'),refCu=n('refCu'),prot=n('proteccion'),pagAg=n('pagableAg'),dedAg=n('deducAg'),refAg=n('refAg'),pagAu=n('pagableAu'),dedAu=n('deducAu'),refAu=n('refAu'),maquila=n('maquila'),analisis=n('analisis'),traslado=n('traslado'),alquiler=n('alquiler'),adelanto=n('adelanto');
  const tmh=tonelaje*leyCu*3.3/100,tmns=tmh*(1-h2o/100)-tmh*merma/100,contCu=(leyConc-dedCu)/100,cuVal=contCu*1000*(cu-prot)/.45359,contAg=leyAg*pagAg/100,agVal=contAg*(ag-dedAg),contAu=leyAu*pagAu/100,auVal=contAu*(au-dedAu),pago=cuVal+agVal+auVal,ref=contCu*1000*refCu/.45359+contAg*refAg+contAu*refAu,red=maquila+ref+(tmns?analisis/tmns:0)+(tmns?traslado/tmns:0),tm=pago-red,neto=tm*tmns*1.18*.9,desc=alquiler*tonelaje+adelanto,total=neto-desc;
  set('outTmns',money(tmns));set('outTotal',money(total));set('outCu',money(cu));set('outTm',money(tm));set('linePago','$'+money(pago));set('lineReducciones','$'+money(red));set('lineNeto','$'+money(neto));set('lineDescuento','$'+money(desc));set('lineTotal',money(total));
  set('pEmpresa',$('empresa').value||'Minero - Yachaq');set('pFecha',dateLabel($('fecha').value));set('pCliente',$('cliente').value||'No especificado');set('pResponsable',$('responsable').value||'No especificado');set('pObservaciones',$('observaciones').value||'Sin observaciones.');set('pTotal',money(total));set('pTonelaje',money(tonelaje)+' TM');set('pTmns',money(tmns)+' TM');set('pCuLey',money(leyConc)+' %');set('pCuPrice','$'+money(cu)+' /lb');set('pCuPay','$'+money(cuVal));set('pAgLey',money(leyAg)+' oz/tm');set('pAgPrice','$'+money(ag)+' /oz');set('pAgPay','$'+money(agVal));set('pAuLey',money(leyAu)+' oz/tm');set('pAuPrice','$'+money(au)+' /oz');set('pAuPay','$'+money(auVal));set('pPago','$'+money(pago));set('pReducciones','$'+money(red));set('pNeto','$'+money(neto));set('pDescuento','$'+money(desc));set('pGrand',money(total));
  return{tonelaje,tmns,total,pago,red,neto,desc,tm};
}

const defaults={tonelaje:150,leyCu:2.2,leyAg:0,leyAu:0,h2o:10.1,merma:1,leyCuConc:25.23,alquiler:55,adelanto:0,cuPrice:6.29,agPrice:57.5,auPrice:4043.6,pagableCu:100,deducCu:1.35,refCu:.19,proteccion:.1,pagableAg:90,deducAg:2,refAg:1.2,pagableAu:90,deducAu:60,refAu:12,maquila:175,analisis:100,traslado:55};
document.querySelectorAll('input,textarea').forEach(el=>el.addEventListener('input',calculate));
function present(){calculate();document.body.classList.add('presenting');$('presentBtn').classList.add('active');$('editBtn').classList.remove('active')}
function edit(){document.body.classList.remove('presenting');$('editBtn').classList.add('active');$('presentBtn').classList.remove('active')}
$('editBtn').onclick=edit;$('presentBtn').onclick=present;$('returnBtn').onclick=edit;$('presentationPdfBtn').onclick=()=>window.print();$('pdfBtn').onclick=()=>{present();setTimeout(()=>window.print(),200)};
$('resetBtn').onclick=()=>{Object.entries(defaults).forEach(([id,value])=>$(id).value=value);$('cliente').value='';$('responsable').value='';$('observaciones').value='';calculate()};
function read(){try{const value=JSON.parse(localStorage.getItem(KEY));return Array.isArray(value)?value:[]}catch{return[]}}
function write(value){localStorage.setItem(KEY,JSON.stringify(value))}
function snapshot(){const values={};[...ids,...metaIds].forEach(id=>values[id]=$(id).value);return{id:crypto.randomUUID?.()||Date.now()+Math.random(),name:'',date:new Date().toISOString(),values,result:calculate()}}
function render(){let data=read(),q=$('search').value.toLowerCase(),sort=$('sort').value;data=data.filter(x=>!q||(x.name||'').toLowerCase().includes(q)||new Date(x.date).toLocaleString('es-PE').toLowerCase().includes(q));data.sort((a,b)=>sort==='old'?new Date(a.date)-new Date(b.date):sort==='high'?b.result.total-a.result.total:sort==='low'?a.result.total-b.result.total:new Date(b.date)-new Date(a.date));$('historyList').innerHTML='';$('empty').style.display=data.length?'none':'block';data.forEach(x=>{const el=document.createElement('article');el.className='history-item';el.innerHTML=`<div class="history-main"><div><div class="history-title">${x.name||'Cálculo sin nombre'}</div><div class="history-date">${new Date(x.date).toLocaleString('es-PE')}</div></div><div class="history-total">$${money(x.result.total)}</div></div><div class="history-details">Tonelaje: ${money(x.result.tonelaje)} TM · Seco: ${money(x.result.tmns)} TM</div><div class="history-actions"><button data-action="load" data-id="${x.id}">Cargar</button><button data-action="rename" data-id="${x.id}">Renombrar</button><button data-action="delete" data-id="${x.id}">Eliminar</button></div>`;$('historyList').appendChild(el)})}
$('saveBtn').onclick=()=>{const item=snapshot();item.name=prompt('Nombre del cálculo:','Liquidación '+dateLabel($('fecha').value))||'Cálculo sin nombre';const data=read();data.unshift(item);write(data);render();alert('Cálculo guardado.')};$('search').oninput=render;$('sort').onchange=render;$('clearBtn').onclick=()=>{if(confirm('¿Borrar todo el histórico?')){localStorage.removeItem(KEY);render()}};$('historyList').onclick=e=>{const button=e.target.closest('button');if(!button)return;const data=read(),item=data.find(x=>String(x.id)===button.dataset.id);if(button.dataset.action==='delete')write(data.filter(x=>String(x.id)!==button.dataset.id));if(button.dataset.action==='rename'&&item){item.name=prompt('Nuevo nombre:',item.name)||item.name;write(data)}if(button.dataset.action==='load'&&item){Object.entries(item.values).forEach(([id,value])=>$(id).value=value);calculate()}render()};calculate();render();
